/**
 * LLMs.txt Generator
 * Generate sitemap-style content listing for AI crawlers
 * Follows the llms.txt specification
 */

import type { LLMsTxtConfig, LLMsTxtItem } from '../types';

/**
 * Generate llms.txt content
 */
export function generateLLMsTxt(config: LLMsTxtConfig): string {
  const parts: string[] = [];

  // Header
  parts.push(`# ${config.siteName}`);
  parts.push('');

  if (config.siteDescription) {
    parts.push(`> ${config.siteDescription}`);
    parts.push('');
  }

  // Custom header text or default
  if (config.headerText) {
    parts.push(config.headerText);
  } else {
    parts.push('This file provides LLM-friendly access to the content on this website.');
  }
  parts.push('');

  // Site info
  parts.push('---');
  parts.push(`- **Site URL**: ${config.siteUrl}`);
  parts.push('- **Format**: Append `?llm=1` to any page URL to get markdown');
  parts.push('---');
  parts.push('');

  // Content listing
  if (config.content.length > 0) {
    parts.push('## Available Content');
    parts.push('');

    for (const item of config.content) {
      const llmUrl = appendQueryParam(item.url, 'llm', '1');

      parts.push(`### [${item.title}](${llmUrl})`);

      if (item.type) {
        parts.push(`- **Type**: ${item.type}`);
      }

      if (item.date) {
        parts.push(`- **Date**: ${item.date}`);
      }

      if (item.description) {
        parts.push(`- **Description**: ${item.description}`);
      }

      parts.push(`- **Markdown URL**: ${llmUrl}`);
      parts.push('');
    }
  }

  // Footer
  parts.push('---');
  parts.push('');

  if (config.footerText) {
    parts.push(config.footerText);
  } else {
    parts.push('*Generated by [next-llm-ready](https://seoengine.ai) - Make your content AI-ready*');
  }

  return parts.join('\n');
}

/**
 * Append query parameter to URL
 */
function appendQueryParam(url: string, key: string, value: string): string {
  const separator = url.includes('?') ? '&' : '?';
  return `${url}${separator}${key}=${value}`;
}

/**
 * Sort content items by date (newest first)
 */
export function sortByDate(items: LLMsTxtItem[]): LLMsTxtItem[] {
  return [...items].sort((a, b) => {
    if (!a.date) return 1;
    if (!b.date) return -1;
    return new Date(b.date).getTime() - new Date(a.date).getTime();
  });
}

/**
 * Filter content by type
 */
export function filterByType(items: LLMsTxtItem[], types: string[]): LLMsTxtItem[] {
  const typeSet = new Set(types.map((t) => t.toLowerCase()));
  return items.filter((item) => !item.type || typeSet.has(item.type.toLowerCase()));
}

/**
 * Create LLMsTxtItem from minimal data
 */
export function createLLMsTxtItem(
  title: string,
  url: string,
  options?: Partial<Omit<LLMsTxtItem, 'title' | 'url'>>
): LLMsTxtItem {
  return {
    title,
    url,
    ...options,
  };
}
